name: "Release Guacamole"

on:
  push:
    branches:
      - main
  # Optionally, trigger manually...
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 2

      - name: Check if version updated
        id: version_check
        run: |
          if [ ! -f scripts/build-guacamole.js ]; then
            echo "scripts/build-guacamole.js does not exist => skipping."
            echo "version_updated=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Checking for changes in the VERSION line of scripts/build-guacamole.js..."

          prev_version=$(git show HEAD~1:scripts/build-guacamole.js | grep 'const VERSION =' | awk -F'= ' '{print $2}' | tr -d ';')

          current_version=$(grep 'const VERSION =' scripts/build-guacamole.js | awk -F'= ' '{print $2}' | tr -d ';')

          echo "Previous version: $prev_version"
          echo "Current version: $current_version"

          if [ "$prev_version" != "$current_version" ]; then
            echo "Package version updated."
            echo "version_updated=true" >> $GITHUB_OUTPUT
          else
            echo "No version update detected."
            echo "version_updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Use node
        if: steps.version_check.outputs.version_updated == 'true'
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "22.x"
          registry-url: https://registry.npmjs.org/

      - name: Install dev dependencies
        if: steps.version_check.outputs.version_updated == 'true'
        run: |
          cd scripts
          npm ci

      - name: Build the package
        if: steps.version_check.outputs.version_updated == 'true'
        run: |
          cd scripts
          npm run build-guacamole

      - name: Test the exports
        if: steps.version_check.outputs.version_updated == 'true'
        run: |
          cd scripts
          npm run test

      - name: Publish to npm
        if: steps.version_check.outputs.version_updated == 'true'
        run: |
          cd guac-dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
